version: '3.8'

services:
  # Development version with hot reload
  taskflow-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      # Convex
      - CONVEX_DEPLOYMENT=${CONVEX_DEPLOYMENT:-dev:taskflow}
      - NEXT_PUBLIC_CONVEX_URL=${NEXT_PUBLIC_CONVEX_URL:-http://127.0.0.1:3210}
      
      # Clerk
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      
      # Stripe
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      
      # Local S3 (MinIO)
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
      - AWS_S3_BUCKET_NAME=taskflow-files
      - AWS_ENDPOINT_URL=http://minio:9000
      - NEXT_PUBLIC_AWS_S3_BUCKET_NAME=taskflow-files
      - NEXT_PUBLIC_AWS_REGION=us-east-1
      
      # Development
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - minio
    networks:
      - taskflow-dev

  # MinIO for local S3 testing
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_dev_data:/data
    networks:
      - taskflow-dev

  # MinIO setup
  minio-setup:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/taskflow-files --ignore-existing;
      /usr/bin/mc policy set public myminio/taskflow-files;
      echo 'MinIO development setup complete';
      "
    networks:
      - taskflow-dev

  # Stripe CLI for development
  stripe-cli:
    image: stripe/stripe-cli:latest
    command: >
      sh -c "
      if [ -n '${STRIPE_SECRET_KEY}' ]; then
        stripe listen --forward-to taskflow-dev:3000/api/stripe/webhook --skip-verify
      else
        echo 'STRIPE_SECRET_KEY not set. Please set it in .env.docker'
        sleep infinity
      fi
      "
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
    depends_on:
      - taskflow-dev
    networks:
      - taskflow-dev

volumes:
  minio_dev_data:

networks:
  taskflow-dev:
    driver: bridge
